---
title: "Diesel Receipt Analysis"
output:
  html_document:
    df_print: paged
---

example
```{r}
library(tidyverse)
library(purrr)
library(pdftools)
```

```{r}
fn <- system.file("extdata", "RD-Mortality-Report_2015-18-180531.pdf", package="dslabs")
txt <- str_split(pdf_text(fn), "\n")
```

Get a single page for a single year, here "2017".
```{r}
s <- txt %>% .[[9]]
s <- str_trim(s)
  header_index <- str_which(s, "2015")[1]
  tmp <- str_split(s[header_index], "\\s+", simplify = TRUE)
  month <- tmp[1]
  header <- tmp[-1]
  tail_index  <- str_which(s, "Total")
  n <- str_count(s, "\\d+")
  out <- c(1:header_index, which(n==1), which(n>=28), tail_index:length(s))
  s[-out] %>%
    str_remove_all("[^\\d\\s]") %>%
    str_trim() %>%
    str_split_fixed("\\s+", n = 6) %>%
    .[,1:5] %>%
    as_data_frame() %>% 
    setNames(c("day", header)) %>%
    mutate(month = month,
           day = as.numeric(day)) %>%
    gather(year, deaths, -c(day, month)) %>%
    mutate(deaths = as.numeric(deaths)) %>% 
    filter(year==2017)
```

Get all pages together.
```{r}
#str(txt)
#tab <- map_df(txt, function(s){
  s <- str_trim(s)
  header_index <- str_which(s, "2015")[1]
  tmp <- str_split(s[header_index], "\\s+", simplify = TRUE)
  month <- tmp[1]
  header <- tmp[-1]
  tail_index  <- str_which(s, "Total")
  n <- str_count(s, "\\d+")
  out <- c(1:header_index, which(n==1), which(n>=28), tail_index:length(s))
  s[-out] %>%
    str_remove_all("[^\\d\\s]") %>%
    str_trim() %>%
    str_split_fixed("\\s+", n = 6) %>%
    .[,1:5] %>%
    as_data_frame() %>% 
    setNames(c("day", header)) %>%
    mutate(month = month,day = as.numeric(day)) %>%
    gather(year, deaths, -c(day, month)) %>%
    mutate(deaths = as.numeric(deaths))
#})
#tab
```



```{r}
library(tidyverse)
library(pdftools)
```

First read in the pdf file which was created using "Adobe Scan" app.
The scanned pdf file was already run through an OCR scanner in the app.

```{r}
txt <- pdf_text("~/diesel_consumption/Scan 13.03.2019 (1).pdf") %>% str_split("\n") 
#str(txt)
#txt <- txt %>% .[[2]]
receipt <- function(txt) {
  shop <- txt[1] %>% str_trim()
  date <- max(str_extract(txt,"\\d{2}\\s?\\.\\s?\\d{2}\\s?\\.\\s?\\d{4}"), na.rm=TRUE)
  time <- max(str_extract(txt,"\\d{2}\\s?\\:\\s?\\d{2}\\s?\\:\\s?\\d{2}"), na.rm=TRUE)
  value <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\EUR"), na.rm=TRUE)
  liter <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\Lite\\s?r"), na.rm=TRUE)
  price <- max(str_extract(txt,"\\d{1}\\s?\\,\\s?\\d{3}\\s?\\EUR\\/Li\\s?ter"), na.rm=TRUE)  
  c(date,value,liter,price,shop)
}
receipt_mat <- lapply(txt,receipt)
str(receipt_mat)
#receipt(txt)
```

```{r}
txt <- pdf_text("~/diesel_consumption/Scan 18.03.2019.pdf") %>% str_split("\n") #%>% .[[1]]
receipt <- function(txt) {
  shop <- txt[1] %>% str_trim()
  date <- max(str_extract(txt,"\\d{2}\\s?\\.\\s?\\d{2}\\s?\\.\\s?\\d{4}"), na.rm=TRUE)
  time <- max(str_extract(txt,"\\d{2}\\s?\\:\\s?\\d{2}\\s?\\:\\s?\\d{2}"), na.rm=TRUE)
  value <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\EUR"), na.rm=TRUE)
  liter <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\Lite\\s?r"), na.rm=TRUE)
  price <- max(str_extract(txt,"\\d{1}\\s?\\,\\s?\\d{3}\\s?\\EUR\\/Li\\s?ter"), na.rm=TRUE)  
  c(date,value,liter,price,shop)
}
receipt_mat <- lapply(txt,receipt)
str(receipt_mat)
```

```{r}
txt <- pdf_text("~/diesel_consumption/Scan 13.03.2019 (2).pdf") %>% str_split("\n")# %>% .[[1]]
receipt <- function(txt) {
  shop <- txt[1] %>% str_trim()
  date <- max(str_extract(txt,"\\d{2}\\s?\\.\\s?\\d{2}\\s?\\.\\s?\\d{4}"), na.rm=TRUE)
  time <- max(str_extract(txt,"\\d{2}\\s?\\:\\s?\\d{2}\\s?\\:\\s?\\d{2}"), na.rm=TRUE)
  value <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\EUR"), na.rm=TRUE)
  liter <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\Lite\\s?r"), na.rm=TRUE)
  price <- max(str_extract(txt,"\\d{1}\\s?\\,\\s?\\d{3}\\s?\\EUR\\/Li\\s?ter"), na.rm=TRUE)  
  c(date,value,liter,price,shop)
}
receipt_mat <- lapply(txt,receipt)
str(receipt_mat)
```


```{r}
txt <- pdf_text("~/diesel_consumption/Scan 13.03.2019 (3).pdf") %>% str_split("\n") 
receipt <- function(txt) {
  shop <- txt[1] %>% str_trim()
  date <- max(str_extract(txt,"\\d{2}\\s?\\.\\s?\\d{2}\\s?\\.\\s?\\d{4}"), na.rm=TRUE)
  time <- max(str_extract(txt,"\\d{2}\\s?\\:\\s?\\d{2}\\s?\\:\\s?\\d{2}"), na.rm=TRUE)
  value <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\EUR"), na.rm=TRUE)
  liter <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\Lite\\s?r"), na.rm=TRUE)
  price <- max(str_extract(txt,"\\d{1}\\s?\\,\\s?\\d{3}\\s?\\EUR\\/Li\\s?ter"), na.rm=TRUE)  
  c(date,value,liter,price,shop)
}
receipt_mat <- lapply(txt,receipt)
str(receipt_mat)
```

```{r}
txt <- pdf_text("~/diesel_consumption/Scan 29.09.2018 (2).pdf") %>% str_split("\n") 
receipt <- function(txt) {
  shop <- txt[1] %>% str_trim()
  date <- max(str_extract(txt,"\\d{2}\\s?\\.\\s?\\d{2}\\s?\\.\\s?\\d{4}"), na.rm=TRUE)
  time <- max(str_extract(txt,"\\d{2}\\s?\\:\\s?\\d{2}\\s?\\:\\s?\\d{2}"), na.rm=TRUE)
  value <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\EUR"), na.rm=TRUE)
  liter <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\Lite\\s?r"), na.rm=TRUE)
  price <- max(str_extract(txt,"\\d{1}\\s?\\,\\s?\\d{3}\\s?\\EUR\\/Li\\s?ter"), na.rm=TRUE)  
  c(date,value,liter,price,shop)
}
receipt_mat <- lapply(txt,receipt)
str(receipt_mat)
```

```{r}
txt <- pdf_text("~/diesel_consumption/Scan 29.09.2018 (1).pdf") %>% str_split("\n") 
receipt <- function(txt) {
  shop <- txt[1] %>% str_trim()
  date <- max(str_extract(txt,"\\d{2}\\s?\\.\\s?\\d{2}\\s?\\.\\s?\\d{4}"), na.rm=TRUE)
  time <- max(str_extract(txt,"\\d{2}\\s?\\:\\s?\\d{2}\\s?\\:\\s?\\d{2}"), na.rm=TRUE)
  value <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\EUR"), na.rm=TRUE)
  liter <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\Lite\\s?r"), na.rm=TRUE)
  price <- max(str_extract(txt,"\\d{1}\\s?\\,\\s?\\d{3}\\s?\\EUR\\/Li\\s?ter"), na.rm=TRUE)  
  c(date,value,liter,price,shop)
}
receipt_mat <- lapply(txt,receipt)
str(receipt_mat)
#%>% .[[1]]
#txt 
```

```{r}
txt <- pdf_text("~/diesel_consumption/Scan 29.09.2018.pdf") %>% str_split("\n") 
receipt <- function(txt) {
  shop <- txt[1] %>% str_trim()
  date <- max(str_extract(txt,"\\d{2}\\s?\\.\\s?\\d{2}\\s?\\.\\s?\\d{4}"), na.rm=TRUE)
  time <- max(str_extract(txt,"\\d{2}\\s?\\:\\s?\\d{2}\\s?\\:\\s?\\d{2}"), na.rm=TRUE)
  value <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\EUR"), na.rm=TRUE)
  liter <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\Lite\\s?r"), na.rm=TRUE)
  price <- max(str_extract(txt,"\\d{1}\\s?\\,\\s?\\d{3}\\s?\\EUR\\/Li\\s?ter"), na.rm=TRUE)  
  c(date,value,liter,price,shop)
}
receipt_mat <- lapply(txt,receipt)
str(receipt_mat)
```


```{r}
txt <- pdf_text("~/diesel_consumption/Scan 26.03.2019.pdf") %>% str_split("\n") 
receipt <- function(txt) {
  shop <- txt[1] %>% str_trim()
  date <- max(str_extract(txt,"\\d{2}\\s?\\.\\s?\\d{2}\\s?\\.\\s?\\d{4}"), na.rm=TRUE)
  time <- max(str_extract(txt,"\\d{2}\\s?\\:\\s?\\d{2}\\s?\\:\\s?\\d{2}"), na.rm=TRUE)
  value <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\EUR"), na.rm=TRUE)
  liter <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\Lite\\s?r"), na.rm=TRUE)
  price <- max(str_extract(txt,"\\d{1}\\s?\\,\\s?\\d{3}\\s?\\EUR\\/Li\\s?ter"), na.rm=TRUE)  
  c(date,value,liter,price,shop)
}
receipt_mat <- lapply(txt,receipt)
str(receipt_mat)
```

```{r}
txt <- pdf_text("~/diesel_consumption/Scan 03.04.2019.pdf") %>% str_split("\n") 
receipt <- function(txt) {
  shop <- txt[1] %>% str_trim()
  date <- max(str_extract(txt,"\\d{2}\\s?\\.\\s?\\d{2}\\s?\\.\\s?\\d{4}"), na.rm=TRUE)
  time <- max(str_extract(txt,"\\d{2}\\s?\\:\\s?\\d{2}\\s?\\:\\s?\\d{2}"), na.rm=TRUE)
  value <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\EUR"), na.rm=TRUE)
  liter <- max(str_extract(txt,"\\d{2}\\s?\\,\\s?\\d{2}\\s?\\Lite\\s?r"), na.rm=TRUE)
  price <- max(str_extract(txt,"\\d{1}\\s?\\,\\s?\\d{3}\\s?\\EUR\\/Li\\s?ter"), na.rm=TRUE)  
  c(date,value,liter,price,shop)
}
receipt_mat <- lapply(txt,receipt)
str(receipt_mat)
```

```{r}
txt <- pdf_text("~/diesel_consumption/Tankprotokoll.pdf") %>% str_split("\n") %>% .[[1]]
txt 
```